### PR TITLE
Adding Optional bats-core Extensions

### PR DESCRIPTION
**Pull request by qec-pconner**
Extending bazel_bats_dependencies() to also (optionally) allow for adding in bats extensions, bats-assert and bats-support (bats-support is required for bats-assert).

The decision to make these optional additions was made to not force extra dependencies on any downstream library that does not make use of them (dep management is good).
The `bats_test()` rule will be updated in a follow-up PR.

Merge this PR after https://github.com/filmil/bazel-bats/pull/9 (diff will also be easier to read once that PR is merged).
Merge this PR before https://github.com/filmil/bazel-bats/pull/11.

Submitting as separate PRs to more easily see what is changing. :smile:

### CODE REVIEW

**Comment by qec-pconner** [comment]
This PR is mostly good to go -- *though* I would like to first merge master back in after https://github.com/filmil/bazel-bats/pull/9 has been merged to get a nice clean diff. :)

**Comment by qec-pconner** [comment]
Ok. This PR should now be good to go.

**Comment by filmil** [comment]
Care to rebase?

**Comment by filmil** [comment]
Hm, still conflicting.

**Comment by qec-pconner** [comment]
> Care to rebase?

Merged from master (I don't rebase with PR reviews as GitHub annoyingly tosses out old blobs).

**Comment by qec-pconner** [comment]
> Hm, still conflicting.

image
🤷

**Comment by qec-pconner** [comment]
Not sure how the project is set up, but squashing may be necessary on merge. Sorry, not sure where the conflict is.

**Comment by filmil** [comment]
Looking.

**Pull request merged**
