### PR TITLE
Pin the version of ubuntu

### PR DESCRIPTION
**Pull request by filmil**
Fix the SHA256 used for the ubuntu docker image for running tests. This provides a more predictable environment to run the tests in.

Issue: #9

### CODE REVIEW

**Comment by qec-pconner** [comment]
Looking through https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on, it seems that the `runs-on` label does determine the OS that is run, but also is limited to short list of pre-allotted values (e.g. `ubuntu-latest`). So the jobs are likely not running due to a simple syntax error (`runs-on` must be one of the pre-allotted values).

It seems that `ubuntu-latest` was updated around EoY 2020. So, it's still a mystery as to what changed to cause this issue.

If you want to pin to a specific docker image (which is generally a very good idea), you can use `uses` on the specific action in the CI. This would look like:
```
      - name: Test
        uses: ubuntu@sha256:a8fe6fd30333dc60fc5306982a7c51385c2091af1e0ee887166b40a905691fd0
        run: "bazel test //..."
```

I _think_ that should work. IIUC, the `uses` label sets a docker image to run the `run` inside, on top of the `ubuntu-latest` base image. (There are other uses for `uses` for other types of actions, but I'm omitting that). I'm not familiar with the specific ubuntu image that you selected, but if you run that locally and it does not contain `parallel`, then it should be a good pick. Sorry that I'm not more certain about all of this, I'm much much more familiar with [GitLab](https://about.gitlab.com/)'s CI/CD environment/syntax (which is a bit more straightforward / less fancy).

**Comment by filmil** [comment]
Understood, thank you for verifying. I should probably start using `act` to check the actions ahead of sending a PR.
I assumed that there was a task scheduling issue, so I just left it to run and went about my day. But as it usually goes, it didn't pan out.
But we have a clear plan on what to do next, so that should be OK.

**Comment by filmil** [comment]
Unfortunately, it seems that `uses` and `runs` are mutually exclusive, which puts a damper into what we can do about the build reproducibility.

I am reluctant to have to build a custom container to test this stuff.  Let's see if it helps to kind-of pin the edition of ubuntu for `runs-on`.

**Comment by filmil** [comment]
Let's see if this helps.

**Pull request merged**
