### PR TITLE
Fixing Missing `load()`

### PR DESCRIPTION
**Pull request by CauhxMilloy**
* Adding missing `load()` for `maybe()`.

### CODE REVIEW

**Comment by CauhxMilloy** [comment]
Sorry for overlooking this. 😅

**Comment by filmil** [comment]
What worries me now is that it is broken, and yet it passed the presubmit checks. What gives?

**Comment by CauhxMilloy** [comment]
Well, I noticed this weekend that there was no CI running. I didn't think too much of it at first, but then this happened. Looking at the [PR list](https://github.com/filmil/bazel-bats/pulls?q=is%3Apr+is%3Aclosed), it shows that CI ran for all the old PRs but not the last 2. The last CI ran was on my last PR in March. So something is definitely broken with GH just running CI.

**Comment by CauhxMilloy** [comment]
I think I found it (maybe). I can't see this issue on this repo, because I'm not the/an owner. But, on my fork of this repo, I see that Actions are disabled. Going to the Actions tab, I see:
image
When I click on one of those, I see:
image

So this seems like some sort of new change on GH to just disable all CI checking on low activity repos (which seems, y'know, dumb lol).

**Comment by filmil** [comment]
Turns out the workflows were disabled for inactivity.  Which kind of makes sense since it's a low activity repo. I just forgot that this happened.

I re-enabled the workflows.

**Comment by filmil** [comment]
OK, so this change still resulted in a broken post-submit. Sorry for the confusion around workflows.

**Comment by CauhxMilloy** [comment]
> OK, so this change still resulted in a broken post-submit. Sorry for the confusion around workflows.

Np. Sorry about these breaking changes. I can send a PR to try and fix this, if you'd like. (I think its the change to `bazel_skylib` repo).

**Comment by filmil** [comment]
Yes, please.

I think we should just use the regular link to the release archves such as
https://github.com/bazelbuild/bazel-skylib/releases/download/1.5.0/bazel-skylib-1.5.0.tar.gz,
vs the more "exotic" one. Unless I'm missing something?

F

**Comment by CauhxMilloy** [comment]
It was just a missing `/` in the URL. Opened https://github.com/filmil/bazel-bats/pull/34 to fix. Turns out CI is helpful.

I really wish Gitlab would put a notice on PRs to warn about the disabled CI instead of silently letting anything through.

Sorry again for all this.

**Comment by filmil** [comment]
Well I did get a notification that the workflows would be disabled. But I have other things to do besides babysit github, so it fell by the wayside... :/

Now that I know what it means, I will take better care in the future.

**Pull request merged**
