### PR TITLE
Updating bats-core Version

### PR DESCRIPTION
**Pull request by qec-pconner**
* Updating bazel_bats_dependencies()'s default version value (and corresponding SHA) to 1.7.0 (~~latest bats-core version~~a newer version, we can update again later).
* Updating WORKSPACE to be more explicit in versions used.
* Adding param checking to ensure that the SHA was passed in.
* Updating README to show explicit version passing.

Merge this PR after https://github.com/filmil/bazel-bats/pull/8 (diff will also be easier to read once that PR is merged).

Submitting as separate PRs to more easily see what is changing. :smile:

### CODE REVIEW

**Comment by filmil** [comment]
Would you mind resolving the conflict to your liking, and I can merge this.

**Comment by qec-pconner** [comment]
Sorry for the slow turn-around. Merged master back into branch.

I see that one of the bats tests is failing, namely `//tests/bats-core:parallel_test`. It is failing when I run it locally as well. However, it's also failing when I run it locally on `master` (which is still using bats-core 1.5.0) -- so it seems like the version change isn't causing it. Please do let me know if there is anything on my end that's causing the issue. Thanks!

**Comment by qec-pconner** [comment]
After looking at the parallel.bats test a little more, I think I have a guess as to why its failing despite it passing before, see https://github.com/filmil/bazel-bats/pull/8/checks#step:4:37 and https://github.com/filmil/bazel-bats/actions/runs/3211645976/jobs/5249963751#step:4:38.

Looking at the test (as it is failing locally), there are 2 issues.

One issue is that `bats-core/test/parallel.bats` calls to its fixtures (which the bazel targets correctly bring in), but then `bats_core/test/fixtures/parallel/parallel.bats` [calls `load`](https://github.com/bats-core/bats-core/blob/e3bd116fa832e21ea7324eb8aa05594b139d5fcc/test/fixtures/parallel/parallel.bats#L2) on '../../concurrent-coordination', which is not brought in through the bazel target. This would be a quick fix, just need to add `"test/concurrent-coordination.bash",` to `:parallel_lib` in `deps.bzl`.

But, if this is the issue, this should have been failing before, right? Well, all of this is skipped if there is no `parallel` command, see https://github.com/bats-core/bats-core/blob/master/test/parallel.bats#L12. Was this being skipped before? Well, running `//tests/bats-core:parallel_test` locally (and it fails) takes ~10 seconds (which makes sense, as the test runs purposefully slow functions). But, looking at the passing CI jobs (linked above), we see it passing < 1s -- which really sounds like a skip. So why does it fail now, and why does it fail locally? As it turns out, Ubuntu comes with _aaaaa_ `parallel`, just not GNU `parallel`. This means that the call to `type -p parallel &>/dev/null` succeeds (as it doesn't check that `--jobs` is supported, just that some `parallel` command exists). So, the CI seems to be using `ubuntu-latest`, which doesn't seem to be an official docker image, so I'm not exactly sure on its release history. But it _seeeeems_ that `ubuntu-latest` now has a `parallel` when it didn't for the CI on https://github.com/filmil/bazel-bats/pull/8. :shrug: I've definitely seen this sort of non-version-pinned CI dependencies causing issues before -- and it always is a surprise.

That's my best guess. TL;DR: `ubuntu-latest` used to not have any `parallel` command, now it does; but still not GNU parallel.

Arguably this is a fix to be applied to `bats-core` (to better check for GNU parallel) and not to this repo. And it seems like its unrelated to this PR, which is good I guess. The appropriate changes for this repo (not part of this PR) would be to add `"test/concurrent-coordination.bash",` to the bazel target, and to change the docker image used for the tests CI job (to either not have parallel at all, or have GNU parallel).

If there's anything that I missed or am wrong about. Please let me know.

**Comment by filmil** [comment]
Thank you for digging into this. It will take me some time to get to
debugging it.

**Comment by filmil** [comment]
I opted for a sneaky workaround - I'm going to pin the build and test environments to a SHA256 of the official ubuntu images, which does not have `parallel`, GNU or otherwise.  And it also resolves the issue with a moving docker tag.

This should remove the failure if I understood your explanation well, and we can unblock your PRs and check what to do with `bats_core` as the next step.

**Comment by filmil** [comment]
Hm, the sneaky workaround approach didn't work - I thought I could pull a specific Docker tag, but that only caused the actions to stall indefinitely. Back to the drawing board!

**Comment by qec-pconner** [comment]
> I opted for a sneaky workaround

Hehe, I wouldn't really call version locking a "sneaky workaround". I think version locking is a pretty good way to structure projects and ensure stability (also security).

> the sneaky workaround approach didn't work - I thought I could pull a specific Docker tag, but that only caused the actions to stall indefinitely.

I think it should work with some minor changes. I commented in more detail on https://github.com/filmil/bazel-bats/pull/12.

**Comment by filmil** [comment]
@qec-pconner I disabled `//tests/bats-core:parallel_test` for now, and filed Issue #13.

Can you rebase and retry when able?

**Comment by qec-pconner** [comment]
Alright, this PR should be good to go.

**Review by filmil — APPROVED** [review]
This is an easy change, and seems to unblock other work. So let's get that merged quickly.

**Pull request merged**
